server:
  port: 8080

spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            food-user-service:
              - uri: http://localhost:8101
            food-business-service:
              - uri: http://localhost:8201
            food-trade-service:
              - uri: http://localhost:8301
    gateway:
      default-filters:
        - PreserveHostHeader
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            exposedHeaders:
              - authorization
              - X-Trace-Id
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: food-user-route
          uri: lb://food-user-service
          predicates:
            - Path=/api/user/**
        - id: food-business-route
          uri: lb://food-business-service
          predicates:
            - Path=/api/shop-category/**,/api/shop/**,/api/package/**,/api/shop-homepage/**,/api/reviews/**,/api/favorites/shops/**
        - id: food-trade-route
          uri: lb://food-trade-service
          predicates:
            - Path=/api/trade/**

logging:
  level:
    org.springframework.cloud.gateway: info
