server:
  port: 8201

spring:
  application:
    name: food-business-service
  cloud:
    sentinel:
      transport:
        port: ${SENTINEL_BUSINESS_TRANSPORT_PORT:8720}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/food_business_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

food:
  mq:
    review-created-queue: food.business.review.created.queue
    package-stock-event-queue: food.business.package.stock.event.queue
  auth:
    include-paths:
      - /**
    exclude-paths:
      - /health
      - /api/shop-category/**
      - /api/shop/**
      - /api/package/**
      - /api/internal/package/**
