spring:
  application:
    name: food-business-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  cloud:
    nacos:
      config:
        import-check:
          enabled: false

---
spring:
  config:
    activate:
      on-profile: nacos
    import:
      - optional:nacos:food-common.yaml?group=${NACOS_CONFIG_GROUP:FOOD_LIFE_AGENT}&refreshEnabled=true
      - optional:nacos:food-business-service.yaml?group=${NACOS_CONFIG_GROUP:FOOD_LIFE_AGENT}&refreshEnabled=true
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      discovery:
        enabled: ${NACOS_DISCOVERY_ENABLED:true}
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_DISCOVERY_GROUP:FOOD_LIFE_AGENT}
      config:
        enabled: ${NACOS_CONFIG_ENABLED:true}
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_CONFIG_GROUP:FOOD_LIFE_AGENT}
        file-extension: yaml
